services:
  postgres:
    image: postgres:15-alpine
    container_name: career-compass-postgres
    environment:
      POSTGRES_DB: career_compass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - career-compass-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d career_compass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  career-compass-network:
    driver: bridge
